changes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,7 +6,12 @@ on:
       version:
         description: 'Version name'
         required: true
-        default: 'v1.0.0'
+        default: 'minor'
+        type: choice
+        options:
+          - major
+          - minor
+          - patch
 
 jobs:
   release:
@@ -30,10 +35,39 @@ jobs:
         id: determine_version
         run: |
           echo "::set-output name=version::${{ github.event.inputs.version }}"
+      - name: Get previous tag
+          id: previous_tag
+          run: |
+            echo "::set-output name=tag::$(npm version ${{ github.event.inputs.version }})"
+        - name: Determine next version
+          id: determine_version
+          run: |
+            previous_tag=${{ steps.previous_tag.outputs.tag }}
+            major=$(echo $previous_tag | cut -d. -f1)
+            minor=$(echo $previous_tag | cut -d. -f2)
+            patch=$(echo $previous_tag | cut -d. -f3)
+            version=${{ github.event.inputs.version }}
 
+            if [ "$version" == "major" ]; then
+              major=$((major + 1))
+              minor=0
+              patch=0
+            elif [ "$version" == "minor" ]; then
+              minor=$((minor + 1))
+              patch=0
+            elif [ "$version" == "patch" ]; then
+              patch=$((patch + 1))
+            else
+              echo "Invalid version input"
+              exit 1
+            fi
+
+            next_version="$major.$minor.$patch"
+            echo "::set-output name=version::$next_version"
       - name: Tag the commit
         run: |
-          git tag -a "${{ steps.determine_version.outputs.version }}" -m "Version ${{ steps.determine_version.outputs.version }}"
+          next_version=${{ steps.determine_version.outputs.version }}
+          git tag -a "$next_version" -m "Version $next_version"
           git push --follow-tags
       - name: Create release
         id: create_release
